# Generated by Django 5.2 on 2025-04-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_creation_date_answer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color_class',
            field=models.CharField(blank=True, default='bg-primary', max_length=20),
        ),
    ]
