# Generated by Django 5.2 on 2025-05-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_profile_total_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color_class',
            field=models.CharField(blank=True, default='primary', max_length=20),
        ),
    ]
