# Generated by Django 5.2 on 2025-05-24 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_tag_color_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='app_answer_questio_d80d42_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['-created_at'], name='app_answer_created_19565a_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_correct'], name='app_answer_is_corr_1bd605_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', '-is_correct', '-created_at'], name='app_answer_questio_b5d6a0_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['author'], name='app_answer_author__e758b9_idx'),
        ),
        migrations.AddIndex(
            model_name='answerlike',
            index=models.Index(fields=['answer'], name='app_answerl_answer__86f0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='answerlike',
            index=models.Index(fields=['user'], name='app_answerl_user_id_07c6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='answerlike',
            index=models.Index(fields=['is_positive'], name='app_answerl_is_posi_80872f_idx'),
        ),
        migrations.AddIndex(
            model_name='answerlike',
            index=models.Index(fields=['answer', 'is_positive'], name='app_answerl_answer__7311a5_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-created_at'], name='app_questio_created_c70eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='app_questio_is_acti_bf2036_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['author'], name='app_questio_author__cf1ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active', '-created_at'], name='app_questio_is_acti_8d2733_idx'),
        ),
        migrations.AddIndex(
            model_name='questionlike',
            index=models.Index(fields=['question'], name='app_questio_questio_33fcef_idx'),
        ),
        migrations.AddIndex(
            model_name='questionlike',
            index=models.Index(fields=['user'], name='app_questio_user_id_901983_idx'),
        ),
        migrations.AddIndex(
            model_name='questionlike',
            index=models.Index(fields=['is_positive'], name='app_questio_is_posi_182486_idx'),
        ),
        migrations.AddIndex(
            model_name='questionlike',
            index=models.Index(fields=['question', 'is_positive'], name='app_questio_questio_352bc4_idx'),
        ),
    ]
